export const brands = [
  { id: 1, name: "A few moments" },
  { id: 2, name: "A SECRET KNOWLEDGE" },
  { id: 3, name: "A'Pieu" },
  { id: 4, name: "A-dam" },
  { id: 5, name: "A-Derma" },
  { id: 6, name: "AnaMi" },
  { id: 7, name: "Art-Visage" },
  { id: 8, name: "Glow Me" },
  { id: 9, name: "Elian Russia" },
  { id: 10, name: "Influence Beauty" },
  { id: 11, name: "Kristall Minerals" },
  { id: 12, name: "Levrana" },
  { id: 13, name: "Marvel WHITE" },
  { id: 14, name: "Masura" },
  { id: 15, name: "Mirra" },
  { id: 16, name: "OK Beauty" },
  { id: 17, name: "Russian Beauty Guru" },
  { id: 18, name: "Ruta" },
  { id: 19, name: "Sergey Naumov" },
  { id: 20, name: "Shik" },
  { id: 21, name: "S&P" },
  { id: 22, name: "Tint Berry" },
  { id: 23, name: "Tammy Tanuka" },
];
